language: go

before_install:
  - sudo apt-get install gfortran

install:
  - go get -d -t ./...

  - (cd $HOME/gopath/src/github.com/ready-steady/hotspot && git submodule init)
  - (cd $HOME/gopath/src/github.com/ready-steady/hotspot && git submodule update)
  - (cd $HOME/gopath/src/github.com/ready-steady/hotspot && make install)

  - (cd $HOME/gopath/src/github.com/ready-steady/linear/lapack && git submodule init)
  - (cd $HOME/gopath/src/github.com/ready-steady/linear/lapack && git submodule update)
  - (cd $HOME/gopath/src/github.com/ready-steady/linear/lapack && make install)

notifications:
  email:
    on_success: never
